/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package depotsurabaya;

import static depotsurabaya.Login.txt_pass;
import static depotsurabaya.Login.txt_user;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
public class HomeAdmin extends javax.swing.JFrame implements Runnable {

    Thread T;
    boolean kanan = true;
    boolean kiri = false;
    boolean berjalan = true;
    int x, y;
    
    static String username;
    public HomeAdmin(String username) {
        initComponents();
        this.username = username;
        setNama(username);
        this.setTitle("Welcome to Depot Surabaya");
        this.setLocationRelativeTo(this);
        x = jLabel2.getX();
        y = jLabel2.getY();
        
        T = new Thread(this);
        T.start();
    }
    
    @Override
    public void run(){
      while (true){
          if(berjalan){
              if(x >= jPanel2.getWidth()-0){
                  kiri = true;
                  kanan = false;
              }
          if(kiri){
              x -- ;
              jLabel2.setLocation(x,y);
          }
          if(x<=-550) {
              kanan = true;
              kiri = false;
          }
          if(kanan){
              x ++ ;
              jLabel2.setLocation(x,y);
          }
    }
    try{
        Thread.sleep(10);
    }catch (InterruptedException ex){
        Logger.getLogger(HomeAdmin.class.getName()).log(Level.SEVERE,null, ex);
    }
    repaint();
    }
}
    
   public void setNama(String user){
        namahomeadmin.setText(user);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_Dasboard = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        btn_penjualan = new javax.swing.JButton();
        btn_pesanan = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        namahomeadmin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Admin,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 150, 40));

        btn_Dasboard.setBorder(null);
        btn_Dasboard.setContentAreaFilled(false);
        btn_Dasboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DasboardActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Dasboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 100, 30));

        btn_menu.setBorder(null);
        btn_menu.setContentAreaFilled(false);
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 70, 30));

        btn_penjualan.setBorder(null);
        btn_penjualan.setContentAreaFilled(false);
        btn_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 20));

        btn_pesanan.setBorder(null);
        btn_pesanan.setContentAreaFilled(false);
        btn_pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesananActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 90, 20));

        btn_laporan.setBorder(null);
        btn_laporan.setContentAreaFilled(false);
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 90, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Jl.Raya Pemogan no 24, Denpasar Selatan, Denpasar, bali");
        jPanel2.add(jLabel2);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 417, 359, 30));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 20, 40, 40));

        namahomeadmin.setBackground(new java.awt.Color(80, 181, 109));
        namahomeadmin.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        namahomeadmin.setBorder(null);
        namahomeadmin.setOpaque(false);
        jPanel1.add(namahomeadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 310, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\DASHBOARD ADMIN (2).png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DasboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DasboardActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_DasboardActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        this.setVisible (false); 
	new Menu(username).setVisible(true);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualanActionPerformed
        // TODO add your handling code here:
        this.setVisible (false); 
	new transaksi_jual_admin(username).setVisible(true);
    }//GEN-LAST:event_btn_penjualanActionPerformed

    private void btn_pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesananActionPerformed
        // TODO add your handling code here:
        this.setVisible (false); 
	new Transaksi_pemesanan_admin(username).setVisible(true);
    }//GEN-LAST:event_btn_pesananActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
        this.setVisible (false); 
	new Laporan(username).setVisible(true);
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int respons = JOptionPane.showConfirmDialog(this, "Yakin Ingin Keluar ?", "Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(respons==JOptionPane.YES_OPTION) {
  
         this.setVisible(false);
        new HalamanUtama().setVisible(true);
        
        }
        txt_user.setText(null);
        txt_pass.setText(null);
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Dasboard;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_pesanan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namahomeadmin;
    // End of variables declaration//GEN-END:variables
}
