/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package depotsurabaya;

import static depotsurabaya.HomeAdmin.username;
import static depotsurabaya.transaksi_jual_admin.gtotal;
import static depotsurabaya.transaksi_jual_admin.txt_nota;
import java.awt.*;
import java.io.File;
import java.sql.*;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static depotsurabaya.transaksi_jual_admin.txt_tglpenjualan;

public class Pembayaran_penjualan extends javax.swing.JFrame {

    static String username;
    public Pembayaran_penjualan(String username) {
        initComponents();
        this.username = username;
        
        muncul();
        noedit();
        pnj();
    }
    
    private void muncul(){
    txt_nota1.setText(txt_nota.getText());
    
    }

    private void kembalian(){
         
    int gtotal = Integer.parseInt(txt_total1.getText());
    int bayar = Integer.parseInt(txt_bayar.getText());
   
    int kembali  = bayar - gtotal;
    txt_kembalian.setText(String.valueOf(kembali));
    }

    private void noedit(){
    txt_nota1.setEditable(false);
    txt_tgl1.setEditable(false);
    txt_total1.setEditable(false);
    
    }

   private void pnj(){
    try{
        String sql = "SELECT sum(detail_penjualan.sub_total), penjualan.tgl_penjualan "
                + " FROM penjualan join detail_penjualan "
                + " on penjualan.nota_penjualan = detail_penjualan.nota_penjualan"
                + " WHERE penjualan.nota_penjualan='"+txt_nota1.getText() +"'";
            java.sql.Connection conn=(Connection)DepotSurabaya.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if(rs.next()){
            txt_total1.setText(rs.getString(1));
            txt_tgl1.setText(rs.getString(2));
            }else {
                JOptionPane.showMessageDialog(null, sql);
            }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nota1 = new javax.swing.JTextField();
        txt_tgl1 = new javax.swing.JTextField();
        txt_total1 = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();
        txt_kembalian = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nota1.setBorder(null);
        txt_nota1.setOpaque(false);
        jPanel1.add(txt_nota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 122, 166, 26));

        txt_tgl1.setBorder(null);
        txt_tgl1.setOpaque(false);
        jPanel1.add(txt_tgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 186, 167, 25));

        txt_total1.setBorder(null);
        txt_total1.setOpaque(false);
        jPanel1.add(txt_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 249, 167, 24));

        txt_bayar.setBorder(null);
        txt_bayar.setOpaque(false);
        txt_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bayarKeyReleased(evt);
            }
        });
        jPanel1.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 303, 167, 26));

        txt_kembalian.setBorder(null);
        txt_kembalian.setOpaque(false);
        jPanel1.add(txt_kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 359, 167, 25));

        btn_simpan.setBorder(null);
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 420, 122, 27));

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 20, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\PEMBAYARAN PENJUALAN.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyReleased
        // TODO add your handling code here:
        kembalian();
    }//GEN-LAST:event_txt_bayarKeyReleased

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        int kembali = Integer.parseInt(txt_kembalian.getText());
        
        if(kembali<0){
                JOptionPane.showMessageDialog(null, "Maaf Uang Pembayaran Kurang!");
                txt_bayar.setText("");
                txt_kembalian.setText("");
            }else{
        try {
            String sql = "UPDATE penjualan SET Bayar ="+txt_bayar.getText()+ ", "
                    + "Kembalian= "+txt_kembalian.getText()+ " WHERE nota_penjualan "
                    + "='"+txt_nota1.getText()+"'";
            java.sql.Connection conn =(Connection)DepotSurabaya.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            //Statement stm = conn.createStatement();          
        try {
              String NamaFile = "C:\\Users\\LENOVO\\Documents\\NetBeansProjects"
                      + "\\DepotSurabaya\\src\\depotsurabaya\\reportnota.jasper";

            HashMap parameter = new HashMap () ;
            parameter.put ("nota_penjualan", txt_nota1.getText()) ;

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection
        ("jdbc:mysql://localhost/house_food","root","");
            File file = new File (NamaFile) ;

            JasperReport jr = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter,con);

            JasperViewer.viewReport( jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, 
                        "Data Tidak Dapat Dicetak"
            +"\n"+e.getMessage(), "Cetak Data", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        }

    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new transaksi_jual_admin(username).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran_penjualan(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JTextField txt_nota1;
    private javax.swing.JTextField txt_tgl1;
    private javax.swing.JTextField txt_total1;
    // End of variables declaration//GEN-END:variables
}
